# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f3bb0e68e7f5d033ac474393599cb0acb485cf1c503beb7f4b945f1f4024c8048caa7d35c09a6ad164cc4b50afce3b4efad68c17a99aa5875231e6d9848672

test:
  secret_key_base: ad44cca71d10378f91fe23825d5b80fe21281d0d72ec794bb9de210fbd8a8dfca3ae84188dce5895424956e9e6c962427014f71713e588704ab0084fbffe2d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
